### ISSUE TITLE
Spelling mistake in Readme.md file flutter_overlay 

### ISSUE THREAD

**Issue by Roshan13046** [maddyb99/flutter_overlay#1]
There is a spelling mistake in the documentation of the Overlay package.
The highlighted "aa" should be changed to "a".
Link: https://pub.dev/packages/overlay
![overlayDocSpellEr](https://user-images.githubusercontent.com/55108788/101862702-e3ed9c80-3b98-11eb-9d6b-c49cb6f8edda.png)

**Comment by Roshan13046** [comment]
I am working on this issue.

**Comment by maddyb99** [comment]
Closed with #2
